# Site settings
title: Tyler Benfield
email: tyler@tylerbenfield.me
description: > # this means to ignore newlines until "baseurl:"
  Tyler Benfield's personal site and blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tylerbenfield.me" # the base hostname & protocol for your site
github_username:  code-maverick
linkedin:         tylerbenfield
google_plus:      TylerBenfield0
profile_image: "//gravatar.com/avatar/50655d95e83ea135dc94bb0f9e707df9?size=200"

# Build settings
markdown: kramdown
exclude:
- Dockerfile

# Plugins
plugins:
- jekyll-redirect-from